### ISSUE TITLE
Pebble wheels pushed to PyPI are incorrectly tagged

### ISSUE THREAD

**Issue by wimglenn** [noxdafox/pebble#108]
```
docker run --rm -it python:2 bash
root@209f46cb61b0:/# python2 -m pip install pebble
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting pebble
  Downloading Pebble-5.0.1-py2.py3-none-any.whl (29 kB)
Installing collected packages: pebble
Successfully installed pebble-5.0.1
WARNING: You are using pip version 20.0.2; however, version 20.3.4 is available.
You should consider upgrading via the '/usr/local/bin/python2 -m pip install --upgrade pip' command.
root@209f46cb61b0:/# python
Python 2.7.18 (default, Apr 21 2020, 09:53:40) 
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pebble
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/pebble/__init__.py", line 18, in <module>
    from pebble.decorators import synchronized, sighandler
  File "/usr/local/lib/python2.7/site-packages/pebble/decorators.py", line 48
    def decorate_synchronized(function: Callable, lock: threading.Lock) -> Callable:
                                      ^
SyntaxError: invalid syntax
```

The problem is that the code is Python 3 only, however the wheel published to PyPI is tagged as "universal" (`Pebble-5.0.1-py2.py3-none-any.whl` advertises Python 2 compatibility).

The unfortunate result is that this bombs out the CI of any projects which use Pebble as a dependency and still want to support 2.x (ref: https://github.com/wimglenn/advent-of-code-data/pull/77).

The solution is to specify a lower bound on the required Python version using the metadata field [Requires-Python](https://packaging.python.org/en/latest/specifications/core-metadata/#requires-python). This means a pip running on an an older interpreter will ignore incompatible releases, and collect the older release which is still working.

**Comment by noxdafox** [comment]
That's a bummer! Sorry for breaking the build. I will look into the PR.

**Comment by noxdafox** [comment]
Release `5.0.2` should fix the issue. I yanked the old broken builds.

Thanks for reporting this and providing hints for fixing!

**Comment by wimglenn** [comment]
Removed my workaround in https://github.com/wimglenn/advent-of-code-data/pull/77/commits/79e229d5da4d87716b8bca212cc5d88566b0f0a8 and the CI passed, so it looks like the "yank" feature worked ok. I appreciate the incredibly fast turnaround on this!
