### ISSUE TITLE
Get information about broken process

### ISSUE THREAD

**Issue by fbaltor** [noxdafox/pebble#117]
Hey, sorry for opening an issue, but is there an easy way to get information about a specific process that raises an error? I am thinking about [this](https://pebble.readthedocs.io/en/latest/#pools) very simple pool example given in the documentation. I would like to be able to get, for example, the PID, the arguments given to the `function`, etc. Is this possible?

**Comment by noxdafox** [comment]
Hello,

I guess you need this for debugging purposes.

The `PID` can be easily logged by your function at start using the `logging` module.

Function arguments can be appended to the `Future` object once returned as in this example:
https://github.com/noxdafox/pebble/issues/100#issuecomment-1194671131

**Comment by fbaltor** [comment]
Nice! But what if I'm using the `map` method of `ProcessPool`?

**Comment by noxdafox** [comment]
You can still do the same. The `map` future returns the results in the same order of submission.

Hence, you can correlate the error with the submitted parameters once you iterate on the results as long as you keep a reference to you parameters list.

The `PID` is rarely useful as `pebble` does not distinguish among the processes. Each free process picks up the next work item and if it crashes is replaced. The only situation where the `PID` might help is in case the OOM killer kicks in and you would like to understand which work unit was consuming so much memory. But even in that case, there is a better approach as documented in [here](https://pebble.readthedocs.io/en/latest/#control-process-resources-usage).

All in all, the [pool](https://en.wikipedia.org/wiki/Thread_pool) of workers design pattern goal is to lift the user from the burden of managing threads/processes. If you find yourself in a situation where you need direct access to a process or a thread, you are using the wrong pattern. At that point, you'd better of spinning and managing your own processes.

**Comment by noxdafox** [comment]
Closing this issue. Please re-open if the problem persists.
