### ISSUE TITLE
issue with handling frozen exceptions in worker thread or process

### ISSUE THREAD

**Issue by sergeykk** [noxdafox/pebble#125]
When exception is raised in process or thread, pebble handler assign formatted string exception to traceback attribute of upstream exception, however this does not work if exceptions attributed are frozen. As example in jsonschema package, validation raise error jsonschema.exceptions._WrappedReferencingError(err) which is FrozenInstance (using attrs `@frozen`), and when pebble handler tries to set traceback attribute in ` error.traceback = format_exc()`, it fails with another exception: attr.exceptions.FrozenInstanceError

For reference In pebble/common.py code like
```
def process_execute(function, *args, **kwargs):
    """Runs the given function returning its results or exception."""
    try:
        return Result(SUCCESS, function(*args, **kwargs))
    except BaseException as error:
        error.traceback = format_exc()
        return Result(FAILURE, RemoteException(error, error.traceback))
```

example traceback:
```
"/spare/local/condacem/.micromamba/2dab20714f8ac239b33db413c3d6d73a/lib/python3.11/site-packages/pebble/pool/thread.py", line 195, in execute_next_task
    result = execute(payload.function, *payload.args, **payload.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/spare/local/condacem/.micromamba/2dab20714f8ac239b33db413c3d6d73a/lib/python3.11/site-packages/pebble/common.py", line 168, in execute
    error.traceback = format_exc()
    ^^^^^^^^^^^^^^^
  File "/spare/local/condacem/.micromamba/2dab20714f8ac239b33db413c3d6d73a/lib/python3.11/site-packages/attr/_make.py", line 605, in _frozen_setattrs
    raise FrozenInstanceError()
attr.exceptions.FrozenInstanceError
```

**Comment by noxdafox** [comment]
I don't know what kind of lunatic would actually set an exception as a Frozen class. Anyways, the logic now handles this issue but at the cost of losing the traceback as... well... we cannot set it because the exception is frozen.

Issue fixed in release `5.0.7`, please re-open this issue if the problem persists.
