### ISSUE TITLE
Include worker PID in ProcessExpired exception

### ISSUE THREAD

**Issue by rsiemens** [noxdafox/pebble#141]
👋 , we are utilizing the pebble `ProcessPool` quite heavily and occasionally we'll find ourselves needing to debug an abnormal exit on a worker. When `ProcessExpired` is raised in the main processes `done_callback` we get the exit code, which is helpful, but lack the process id of the worker which would make finding logs and sourcing the underlying reason much easier.

Ask:
 - Can we update `handle_worker_expiration` to include the `worker_id` in the `ProcessExpired` exception [here](https://github.com/noxdafox/pebble/blob/master/pebble/pool/process.py#L267)?

**Comment by noxdafox** [comment]
Hello,

thanks for reporting this issue. I will add the `PID` onto the exception.

**Comment by charettes** [comment]
Thanks for your consideration @noxdafox 🙇 Would submitting a PR with tests tweaks ourselves be appreciated or you'd prefer to tackle the feature request yourself?

I see there's [already a test we could adjust for this purpose](https://github.com/noxdafox/pebble/blob/6445f693bc4449bd0467c30af6fa7f4729404163/test/test_process_pool_fork.py#L426-L430)

**Comment by noxdafox** [comment]
Issue resolved in `5.1.0`.

**Comment by charettes** [comment]
Thanks @noxdafox!
