### ISSUE TITLE
Canceling a future before a worker picks it up results in it still executing briefly.

### ISSUE THREAD

**Issue by rsiemens** [noxdafox/pebble#144]
Hey there,

We discovered some behavior that was a little surprising and I'd like to get your take on it. A future that is cancelled before a worker picks it up still ends up running briefly before the worker is sent a SIGTERM to cancel it. The ability of pebble to cancel a running task is awesome, but I'd expect canceling a task before it runs to result in it not running at all. Consider the following script to demonstrate:

```python
import time
from concurrent import futures
from functools import partial

import pebble


def callback(i, f):
    try:
        f.result()
    except futures.CancelledError:
        print(f'{i}: callback - future canclled')
    else:
        print(f'{i}: callback - ok')

    return i


def task(i):
    print(f'{i}: task start')
    time.sleep(10)  # simulate slow I/O like an network call 
    print(f'{i}: task end')


def main():
    inflight = []
    pool = pebble.ProcessPool(max_workers=2)

    # We have 2 workers and 4 tasks. Each task will take ~10sec to complete.
    # While the two workers are saturated there are 2 pending tasks which we
    # will cancel.
    for i in range(4):
        f = pool.schedule(task, args=[i])
        f.add_done_callback(partial(callback, i))
        inflight.append(f)

    # sleep to force a context switch so the `task_scheduler_loop` has a chance
    # to de-queue the tasks and send the to the `pool_manager.schedule()`.
    time.sleep(0.1)
    inflight[2].cancel()
    inflight[3].cancel()
    pool.close()
    pool.join()


if __name__ == '__main__':
    print(f'pebble {pebble.__version__}')
    main()
```

On my Apple M3 Pro (OSX 14.7) this produces the following output:
```
pebble 5.1.0
0: task start
1: task start
2: callback - future canclled
3: callback - future canclled
1: task end
1: callback - ok
2: task start
0: task end
0: callback - ok
3: task start
```

I would not expect to see `2: task start` or `3: task start` since those futures were cancelled _prior_ to the worker running the task.

From how I understand the process pool implementation this behavior occurs because:
- `pool.schedule()` call will simply put the task into the `context.queue: Queue`.
- The `task_scheduler_loop` thread will get the task from the queue and call `pool_manager.schedule()`with the task
-  `pool_manager.schedule` will register and subsequently dispatch the task to the `worker_channel: Pipe` at which point a worker **has** to pick it up.
- The task can then run up until the `pool_manager_loop` calls `pool_manager.update_status` and identifies the canceled task is running and sending SIGTERM to the worker running it.

I think part of the problem is that `context.queue` doesn't back pressure tasks in the queue according to how saturated the workers are so the [check for a canceled future](https://github.com/noxdafox/pebble/blob/master/pebble/pool/process.py#L166) is often too early. I took a peak at how `concurrent.futures` does it and it looks like they limit the number of items in the queue via [`EXTRA_QUEUED_CALLS`](https://github.com/python/cpython/blob/main/Lib/concurrent/futures/process.py#L114-L118).

I believe one possible way pebble could implement something similar is to have a counter/synchronization mechanism on the `context`. The `PoolManager` increments it on the `dispatch` and decrement it on the `process_next_message` for `isinstance(message, (Result, Problem))`. The `task_scheduler_loop` can then choose to not de-queue items and dispatch them until the counter is less than `num_worker + optional_space`. This would keep it's check for `task.future.cancelled()` to as late as possible before the task is sent to a worker.

Looking forward to hearing your thoughts and thanks for taking the time to maintain this!

**Comment by noxdafox** [comment]
Hello,

what you are noticing is expected behaviour and already discussed in [this issue](https://github.com/noxdafox/pebble/issues/33).

When designing pools of workers, one of the core goals is to keep workers as busy as they can. A busy worker is a happy worker. To do so, we stuff the pipe with as many items as we can. If we don't do so, we risk to end up with idle workers.
There are no easy ways around that due to the competition between a single feeder (the main process) a multiple consumers (the workers).

Any attempt to optimize this will end up with idle workers which is less than ideal. This is a trade-off that `concurrent.future.ProcessPoolExecutor` needs to do as it cannot cancel running jobs. Hence, the only way to guarantee a somewhat reliable `Future.cancel` method is to delay the submission to the pipe to the last moment possible.

This issue does not occur in `pebble.ProcessPool` as it is able to cancel running futures. Hence, we optimize for the happy path (which is assumed to be the most frequent) and sacrifice a bit of performance for the unhappy one.

Attempts to improve these matters have been done in the past but the performance impact has always been considerable.

If you really need to avoid cancelled tasks from being worked on, you can either implement what [suggested](https://github.com/noxdafox/pebble/issues/33#issuecomment-408404961) in the previous issue or simply implement a backpressure mechanism yourself on top of the `ProcessPool`.

**Comment by rsiemens** [comment]
@noxdafox, thank you for your response and sharing some of the context around the decision! I'm a little embarrassed I opened up an issue which a co-worker had previously opened up. My apologies  🙇.

To share a little context on our end - we actually do have some soft back pressure already where we only schedule up 2x the number of workers in tasks to keep them saturated, but not idle. Because our tasks are side-effect heavy we wanted to cancel anything pending ahead of a worker picking it up at pod rotation to minimize the grace period needed to rotate. In the normal case though we don't want to lose the high throughput pebble offers. I think the obvious solution for us is to extend our grace period to allow enough time for all tasks in the buffer to flush out.

Thanks again for taking the time to explain!

**Comment by noxdafox** [comment]
There are two workarounds you can go through.

The first consists in increasing the frequency at which the pool is updating its internal state. At the costs of few more CPU cycles spent on the pool's internals, you can make it more reactive to situations such as cancellation of tasks.

You can do that by intervening on the `pebble.CONST.sleep_unit` (default 0.1 seconds) [constant](https://github.com/noxdafox/pebble/blob/master/pebble/common/types.py#L170).

```python
from pebble import CONSTS

CONSTS.sleep_unit = 0.01
```

The seconds can be achieved by de-creasing the size of the internal pool's pipe using the `fcntl` [syscall](https://docs.python.org/3/library/fcntl.html#fcntl.fcntl). This is quite hacky and could lead to potential issues so beware.

```python
import fcntl 

fcntl.fcntl(pool._pool_manager.worker_manager.workers_channel.fileno(), fcntl.F_SETPIPE_SZ, arg=16384)
```

Both these strategies might bring important side-effects so make sure you test them thoroughly if you choose this path.

**Comment by noxdafox** [comment]
@rsiemens can we close this issue? Are clarifications still needed?

**Comment by rsiemens** [comment]
Sorry, we can close it. 🙇
