### ISSUE TITLE
Latest wheel (4.3.4) is not compatible with Windows?

### ISSUE THREAD

**Issue by freol35241** [noxdafox/pebble#16]
Hi,

Thanks for a nice package!

However, ran in to the following while trying to install pebble on python 3.6 on a windows machine today (I have installed previous releases without any trouble):

Directly through pip + pypi:

`
Collecting pebble
Could not find a version that satisfies the requirement pebble (from versions:
 )
No matching distribution found for pebble
`

And when downloading the wheel manually and trying `pip install *.whl`:

`
Pebble-4.3.4-py2.py3-none-any.whl is not a supported wheel on this platform.
`

**Comment by noxdafox** [comment]
Hello,

are you installing Pebble standalone or as a dependency of another package? 

What is the output for the command:

`pip install -v *.whl`?

**Comment by freol35241** [comment]
Hi,

Quick response! :)

4.3.3 works, just installed it again 10 minutes ago.

The output is as follows:
`
Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
Pebble-4.3.4-py2.py3-none-any.whl is not a supported wheel on this platform.

Exception information:
Traceback (most recent call last):
  File "c:\python36-32\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\python36-32\lib\site-packages\pip\commands\install.py", line 312, in
run
    wheel_cache
  File "c:\python36-32\lib\site-packages\pip\basecommand.py", line 276, in popul
ate_requirement_set
    wheel_cache=wheel_cache
  File "c:\python36-32\lib\site-packages\pip\req\req_set.py", line 245, in add_r
equirement
    wheel.filename
pip.exceptions.InstallationError: Pebble-4.3.4-py2.py3-none-any.whl is not a
 supported wheel on this platform.
`

**Comment by noxdafox** [comment]
I just tried on a Windows 10 machine at it worked flawlessly.

What version of pip do you have? Have you tried updating it to the latest?
`python -m pip install --upgrade pip`

**Comment by freol35241** [comment]
Hmm, I am sitting on a windows 8 machine. pip is the latest version. No luck yet.

**Comment by noxdafox** [comment]
I don't have a Windows 8 machine, I'll try with Windows 7 but I doubt the OS version is the issue.

What is the output of the following command Python script?

```
import pip
print(pip.pep425tags.get_supported())
```

What is the output of the following command?

```
pip -V
```

**Comment by freol35241** [comment]
Ok, finally found the time to backtrack this issue properly. It is related to the folllowing issue [github/pypiserver#179](https://github.com/pypiserver/pypiserver/issues/179) which relates to that pypi.python.org seems to no longer accept http requests (from now on only https requests.

Sorry to bother you about this and thank you for your prompt replies!

**Comment by noxdafox** [comment]
np, glad you solved your problem.
