### ISSUE TITLE
ProcessPool map usage

### ISSUE THREAD

**Issue by akbhat** [noxdafox/pebble#18]
```
def task_done(future):
    try:
        print(future.result())
    except TimeoutError as error:
        logging.error("Function took longer than {} seconds".format(error.args[1]))

with ProcessPool(max_workers=args.workers, initializer=proc_init, initargs=(fail_writer,sw_writer,hw_writer,lks,swfh,hwfh,failfh,compile_re,uname,pwd,r_hash)) as p:
                        future = p.schedule(getAcrDeviceData, args=[devices[0]], timeout=20)
                        future.add_done_callback(task_done)
```
The above works as expected i.e I am able to get the "Function took longer than 20 seconds" but if I use map instead (devices is the iterable), the future returned has the timeout exception but in the task_done the except TimeoutError block does not execute. Am I using map correctly? 

```
with ProcessPool(max_workers=args.workers, initializer=proc_init, initargs=(fail_writer,sw_writer,hw_writer,lks,swfh,hwfh,failfh,compile_re,uname,pwd,r_hash)) as p:
                        future = p.map(getAcrDeviceData, devices, timeout=20)
                        future.add_done_callback(task_done)
```

**Comment by noxdafox** [comment]
The [documentation](https://pebble.readthedocs.io/en/latest/#pools) has some usage examples of `map`. 

The `map` function has been designed to allow the User to retrieve the computation results even in case of error. Python `concurrent.futures.Executor` implementations instead, invalidate the set of results when the first exception is encountered. 

To see the `TimeoutError`, modify the `task_done` function as follows:

```
def task_done(future):
    try:
        iterator = future.result()
        
        for result in iterator:
            print(result)
    except TimeoutError as error:
        logging.error("Function took longer than {} seconds".format(error.args[1])) 
```

**Comment by akbhat** [comment]
Based on the example in the documentation, I changed my code as below:

with ProcessPool(max_workers=args.workers, initializer=proc_init, initargs=(fail_writer,sw_writer,hw_writer,lks,swfh,hwfh,failfh,compile_re,uname,pwd,r_hash)) as p:
    future = p.map(getAcrDeviceData, devices, timeout=20)
    iterator = future.result()

    while True:
        try:
            result = next(iterator)
        except StopIteration:
            break
        except TimeoutError as error:
            logging.error("Function took longer than {} seconds".format(error.args[1]))
        except ProcessExpired as error:
            logging.error("{}. Exit code: {}".format(error, error.exitcode))
        except Exception as e:
            logging.error("{}".format(str(e)))
            logging.exception("Exception!")

As an experiment, map is setup to call the function for two devices, one of which is accessible and so execution is successful. The second is not accessible and hence should timeout. While the timeout happens and "Function took longer than 20 seconds" message is printed, its followed by the below trace.  The device is inaccessible so not sure why the select call is returning an error :(

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pebble/pool/channel.py", line 45, in unix_poll
    return bool(select.select([self.reader], [], [], timeout)[0])
  File "/usr/local/lib/python3.6/multiprocessing/connection.py", line 170, in fileno
    self._check_closed()
  File "/usr/local/lib/python3.6/multiprocessing/connection.py", line 136, in _check_closed
    raise OSError("handle is closed")
OSError: handle is closed

**Comment by noxdafox** [comment]
This seems a bug in `pebble`. It might be a spurious trace log while terminating the Pool. 

Is that all you get as a traceback?

Is the application working correctly nevertheless that error?

**Comment by akbhat** [comment]
The application continues so it does seem to be a spurious trace log. I also noticed that among many runs there maybe a rare occasion when the app completes without the trace.

Complete trace:
[ ERROR] Function took longer than 20 seconds

Process Process-51:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pebble/pool/channel.py", line 45, in unix_poll
    return bool(select.select([self.reader], [], [], timeout)[0])
  File "/usr/local/lib/python3.6/multiprocessing/connection.py", line 170, in fileno
    self._check_closed()
  File "/usr/local/lib/python3.6/multiprocessing/connection.py", line 136, in _check_closed
    raise OSError("handle is closed")
OSError: handle is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/pebble/pool/process.py", line 383, in worker_process
    for task in worker_get_next_task(channel, params.max_tasks):
  File "/usr/local/lib/python3.6/site-packages/pebble/pool/process.py", line 397, in worker_get_next_task
    yield fetch_task(channel)
  File "/usr/local/lib/python3.6/site-packages/pebble/pool/process.py", line 401, in fetch_task
    while channel.poll():
  File "/usr/local/lib/python3.6/site-packages/pebble/pool/channel.py", line 47, in unix_poll
    error = OSError(err.args[1])
IndexError: tuple index out of range

**Comment by noxdafox** [comment]
The complete traceback explains the root cause. 

In Python 3 they reworked the `Exception` hierarchy unifying several different exceptions. This caused the layout of the exception class to change. Hence the error:

```
IndexError: tuple index out of range
``` 

You can consider it a spurious error log. I will fix it ASAP.

**Comment by noxdafox** [comment]
I pushed a small fix in version `4.3.5`.

Could you please test it and let me know if it works?

**Comment by akbhat** [comment]
Pebble 4.3.5 resolves the issue.

Unrelated question: In the exception handling, what is the best way to determine which element of the map iterable timed out? Is there a way to determine the element directly from the future object or some sort of @sighandler((signal.SIGINT, signal.SIGTERM)) on top of the callable which can then print the element before it is cancelled?

**Comment by noxdafox** [comment]
The returned iterable is in the same order than the submitted one. You can simply refer to the element index to know which ones were the problematic.

    index = 0
    devices = [1,2,3]

    ...

    while True:
        try:
            result = next(iterator)
            index += 1
        except StopIteration:
            break
        except TimeoutError as error:            
            print("Error when processing %s" % devices[index])
            index += 1
