### ISSUE TITLE
Limiting memory usage for pool process

### ISSUE THREAD

**Issue by andresriancho** [noxdafox/pebble#22]
I'm using pebble process pool to run python code which I don't fully trust / control. This code is parsing HTML documents and for some specific HTML documents it segfaults, enters and endless loop or consumes a lot of memory.

Pebble allows me to protect my main process from segfaults, and by setting a timeout to the parsing process I'm also protected against endless loops.

What is missing for me now is the case where the parser consumes *a lot* of memory. My ideal scenario would be one where I could tell pebble to kill the process if its memory usage exceeds X number of MB.

There seem to be ways of doing this in regular processes (not related with pebble):
 * https://stackoverflow.com/a/2308635/1347554
 * https://stackoverflow.com/a/30269998/1347554

But before implementing this into my code I was wondering if @noxdafox  had experience doing something like this, ideas, tips, etc. and if you would be interested in me implementing this idea in pebble instead of my code / pebble subclass.

**Comment by noxdafox** [comment]
Hello,

in the past I was thinkering about enhancing Pebble isolation capabilities adding features such as resource limitations etc. What let me wondering was how far to push before actually overlapping with utilities such as `LXC` and `Docker`.

Another challenge is how to ensure portability as you start walking on a OS-specific domain. One of Pebble design principles was the offering of a unified and simple interface (not that we can't change that).

There are plenty of cool tricks to play using either Linux `cgroups`, `ulimit` or simply Python modules.

Pebble `Pool` initializer method already allows the User to play with this idea.

This example limits the total amount of RAM the worker process can use.
```python
import resource

from pebble import ProcessPool

def intializer(memlimit):
    """Set the soft memory limit for the worker process."""
    # retrieve current limits, re-use the hard limit
    soft, hard = resource.getrlimit(resource.RLIMIT_VMEM)
    resource.setrlimit(resource.RLIMIT_VMEM, (memlimit, hard))

# 128 Mb of limit per each process
pool = ProcessPool(initializer=initializer, initargs=[134217728])
```

Nevertheless, if you have some cool idea which would not overly complicate the APIs logic, feel free to share and post a PR. Contributions are welcome.

**Comment by andresriancho** [comment]
I believe that this doesn't overlap with docker, lxc, etc. It is just a new `pebble` feature.

I was thinking about using `initializer` and the `resource` module too. Good to know that we're on the same page.

I'll run some tests and let you know how they went. Maybe if it just works with the code you mention, we can create a `gist` and link it somewhere in the docs. That `gist` is just a recipe which could be used by developers to limit RAM / CPU / etc. using the `resource` module.

**Comment by andresriancho** [comment]
Just wrote some tests to help me understand how this works, and everything seems to be OK:

https://github.com/andresriancho/w3af/blob/155a28c5a337f73d3c21a3cf4ef150d913165173/w3af/core/controllers/threads/tests/test_pebble_limit_memory_usage.py

Some things I noticed:
 * `MemoryError` is raised when the child process exceeds the memory usage, not `ProcessExpiredError` as you mentioned
 * The child process doesn't die! At first I expected [this assertion](https://github.com/andresriancho/w3af/blob/155a28c5a337f73d3c21a3cf4ef150d913165173/w3af/core/controllers/threads/tests/test_pebble_limit_memory_usage.py#L115) to be `assertNotEqual` (meaning that the process was killed by the OS and a new one was spawned by pebble). It seems that python handles the signals sent by the OS and raises MemoryError instead of dying.
 * `RLIMIT_VMEM` did not exist on my OS (ubuntu linux), had to use `RLIMIT_AS` instead. This is a bad signal which seems to indicate that this will work on linux but not on mac (you use mac? and have `RLIMIT_VMEM`?) or other operating systems

**Comment by noxdafox** [comment]
I played with the `resources` library long ago and I remember there was some quirk.

You are right, `ProcessExpiredError` is raised when a process dies unexpectedly but the `resources` library actually raises a `MemoryError` which will be caught and delivered to the `Pool` like any regular Python exception. Pebble does not kill processes if Python exceptions are triggered, it just reports them to the main loop.

The `MemoryError` will interrupt the running routine without actually crashing the process.
I believe this is fine as long as the job logic does not leak some resource such as threads etc.  Otherwise, `ulimit` might be a better option.

Regarding the last point it boils down to what I said in the previous comment: `you start walking on a OS-specific domain`

**Comment by noxdafox** [comment]
Added a [chapter](https://pebble.readthedocs.io/en/latest/#control-process-resources-usage) in the documentation describing how to limit `ProcessPool` worker resources.
