### ISSUE TITLE
Canceling the running future object

### ISSUE THREAD

**Issue by warmspringwinds** [noxdafox/pebble#25]
Hi,

Thank you for the great library :)

Wanted to ask a question regarding your SO answer here:
https://stackoverflow.com/a/45565421

Basically, what exactly happens to a process when the ```cancel()``` is called in
your library?

I wasn't able to fully understand that by looking at your code.

Thank you so much !

**Comment by noxdafox** [comment]
Hello and thanks for using pebble!

In case of `concurrent.process` and `ProcessPool`, when the future is canceled the process will be terminated. This differs from `concurrent.futures.Executor` implementation where a canceled future will not stop the related job from executing. 

This was designed to ensure continuity of operation and predictable performance from the services using pebble. Implementations like `concurrent.futures.Executor` and `multiprocessing.Pool` don't stop timing our or canceled jobs but just ignore their results leaving them crunching in the background. This is far from ideal when you are developing services with the above mentioned requirements.

**Comment by warmspringwinds** [comment]
@noxdafox got it. Thank you :)
