### ISSUE TITLE
Feature Request: Number of processes completed for logging.

### ISSUE THREAD

**Issue by DimitriosTheodorakis** [noxdafox/pebble#27]
In python multiprocessing Manager().Queue() has the function qsize() which returns the number of processes completed or running.
Is there a way of logging how far through all the processes I am with pebble?

**Comment by noxdafox** [comment]
Hello,

this should be rather simple. What about an attribute like:

```python
    pool.statistics
```

**Comment by noxdafox** [comment]
I thought a bit about this feature and realized it does not sound like a good idea for few reasons.

### Added Value

It is very simple to implement such a feature within the application by simply using the `Future.add_done_callback`.

```python
import pebble

DONE = 0

def function(argument):
    return argument

def callback(future):
    global DONE

    DONE += 1

    print(f"Tasks done: {DONE}")

with pebble.ProcessPool() as pool:
    for _ in range(10):
        future = pool.schedule(function)
        future.add_done_callback(callback)
```

Hence embedding this functionality within the Pool adds very little value overall as the amount of lines of code which the Users would save are negligible.

### API design

It becomes very difficult to design a set of API which would satisfy each possible Use Case while still be lean and simple.

Let's look at few of those:
1. I would like to know how many tasks succeeded vs how many failed with an exception
2. I would like to know what types of exceptions were raised within the scheduled function
3. I would like to know how many tasks returned a specific value
4. I would like to know how many tasks took more than a specific amount of time to complete
5. ....

At this point becomes evident that it would be quite hard to design a statistics report which would satisfy all the above. Yet the Users can, based on the example in the previous point, satisfy all their needs with few lines of extra code.

### Overhead

Counting statistics, especially if we want to inspect the results, would add computational overhead. Even if this overhead would be small, it would tax all Pebble Users whether they use the statistics or not.
