### ISSUE TITLE
SystemError: NULL result without error in PyObject_Call

### ISSUE THREAD

**Issue by andresriancho** [noxdafox/pebble#29]
Returning a lot of data from a subprocess will raise an exception:

```python
from pebble import ProcessPool
from concurrent.futures import TimeoutError


def function(foo):
    return 'A' * (10 ** foo)


def task_done(future):
    try:
        result = future.result()  # blocks until results are ready
    except TimeoutError as error:
        print("Function took longer than %d seconds" % error.args[1])
    except Exception as error:
        print("Function raised %s" % error)
        print(error.traceback)  # traceback of the function
    else:
        print(len(result))


pool = ProcessPool(max_workers=5, max_tasks=10)

for i in xrange(11):
    future = pool.schedule(function, args=[i], timeout=20)
    future.add_done_callback(task_done)

pool.close()
pool.join()
```

```
[eth:~/tools/w3af] [w3af] develop* ± python testp.py 
1
10
100
1000
10000
100000
1000000
10000000
100000000
1000000000
Process Process-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/eth/tools/virtualenvs/w3af/local/lib/python2.7/site-packages/pebble/pool/process.py", line 387, in worker_process
    send_result(channel, Result(task.id, result))
  File "/home/eth/tools/virtualenvs/w3af/local/lib/python2.7/site-packages/pebble/common.py", line 163, in send_result
    pipe.send(data)
  File "/home/eth/tools/virtualenvs/w3af/local/lib/python2.7/site-packages/pebble/pool/channel.py", line 97, in unix_send
    return self.writer.send(obj)
SystemError: NULL result without error in PyObject_Call
Function raised Abnormal termination
No handlers could be found for logger "concurrent.futures"
[eth:~/tools/w3af] [w3af] develop* 3s ± 
```

Note that the exception is **NOT** caught by `except Exception as error:` in `task_done`, which makes it impossible to handle.

This issue seems to be known / common:
 * https://bugs.python.org/issue17560
 * https://stackoverflow.com/questions/22656285/multiprocessing-null-result-without-error-in-pyobject-call

And it also seems to be an anti-pattern to send tons of data to / from the subprocess. My goal here is to report this in order to get the conversation started, ultimately I would like this exception to be handled by `pebble` in such a way that I can then handle it in my code.

This issue might be related with https://github.com/noxdafox/pebble/issues/28

**Comment by andresriancho** [comment]
As I mentioned in previous conversations, I use `pebble` to parse HTML in sub-processes (to get isolation since libxml2 sometimes enters an infinite loop when parsing some docs, and to get parallelization).

99,9% of the docs are parsed without issues, but sometimes the doc has lots of links / images / data / etc. which trigger strange errors.

I haven't personally found this specific issue in `w3af` + `pebble`, but I could see someone getting to this issue at some point.

Note: The app crashed when the subprocess tried to return `10 ** 11` == 10G of data to the pipe. Not many users will hit this limit.

**Comment by andresriancho** [comment]
Reproduce with `multiprocessing` library:

```python
#!/usr/bin/env python
"""Try to cause MemoryError by sending large data via multiprocessing.Pipe.
Context: http://stackoverflow.com/q/22150703
"""
from multiprocessing import Process, Pipe

def send_big_data(conn):
    data = b"a" * (1 << 31)
    conn.send(data)
    conn.close() # eof

if __name__=="__main__":
    parent_conn, child_conn = Pipe()
    child = Process(target=send_big_data, args=(child_conn,))
    child.start()
    child_conn.close() # child must be the only with it opened
    print(len(parent_conn.recv()))
```

**Comment by noxdafox** [comment]
Hello,

yes, this and issue #28 are definitely related.

As stated in the [documentation](https://pebble.readthedocs.io/en/latest/#processes):

> The Python’s multiprocessing guidelines apply as well for all functionalities within the process namespace.

From the `multiprocessing` [programming guidelines](https://docs.python.org/3/library/multiprocessing.html#programming-guidelines):

> As far as possible one should try to avoid shifting large amounts of data between processes.

The limit you are encountering in both issues is due to the fact Python tries to enforce OOP on top of concurrency programming which, in my humble opinion, are two design patterns really far from each other.
In Python everything is supposedly an object. This implies that when you send large objects on a `pipe` the interpreter will serialize such object on one side and de-serialize it on the other. As objects get garbage collected once out of scope, you inevitably end up with 2 copies of the same object at a given time. Multiply this by your level of concurrency and you see how easy this can become unstable.

I designed plenty of multiprocessing systems over the years with Python and other languages and one of the things I learned to avoid the most is to use IPC to shift large amount of data. It usually pushes frameworks to the boundaries and it's also utterly slow. 

Note that this limitation comes from the OS itself and not the language.

The pattern I nowadays use is:

- IPC for messages
- Filesystem for data

You would be surprised to notice how faster would your system gets if you stick to the above guideline.

**Comment by noxdafox** [comment]
Regarding the handling of [`SystemError`](https://docs.python.org/3.6/library/exceptions.html#SystemError) I'd rather not. 

It is considered an anti-pattern to catch exceptions superior than `Exception`. They are intended for exceptional cases. In particular, `SystemError` means the Python interpreter has encountered an exceptional error and in that case is better to give up. It would be hard in fact to ensure the consistency of the application in these exceptional cases.

**Comment by andresriancho** [comment]
Thanks for the detailed response, I always learn something new when reading them :+1: 

Regarding handling `SystemError`, I understand that the python interpreter might be in an inconsistent state after it, but what if `pebble` catches the exception, tries to send it to the main thread, and then kills the process (which is in the inconsistent state).

That way the `pebble` user can:
 * Know that the task failed and retry, ignore, stop the whole process, etc.
 * Pebble is not in an inconsistent state, since the process was killed

I'm not sure about other programs, but identifying that this `SystemError` (which is only displayed on stderr and can't be handled by the program) is difficult: the error doesn't appear in the logs, can't catch it with try/except, etc.

Another question, do you also believe that `MemoryError` shouldn't be handled?

**Comment by noxdafox** [comment]
The issue with that strategy is that, as the interpreter might be in an inconsistent state, you might cause more harm than good.

Moreover, the issue should be already covered by Pebble. If the issue happens on the Worker side, as your traceback suggests, the related `Future` object should raise a [`ProcessExpired`](https://pebble.readthedocs.io/en/latest/#pebble.ProcessExpired) error. If it happens within the Pool internals instead the next interaction with it should raise a `RuntimeError`.

Please let me know if the above errors did not happened as this is something to be fixed.

**Comment by andresriancho** [comment]
I'm already handling `ProcessExpired` and `RuntimeError` in my code:

https://github.com/andresriancho/w3af/blob/develop/w3af/core/data/parsers/mp_document_parser.py#L157
https://github.com/andresriancho/w3af/blob/develop/w3af/core/data/parsers/mp_document_parser.py#L178

So that should be covered :+1: I was unaware that MemoryError and SystemError would eventually trigger those two issues. Thanks for clarifying that.

With this new information I believe `pebble` needs no modifications to handle `SystemError` nor `MemoryError`.

Also, I implemented your recommendations on how to send messages and data to the sub-processes:
 * IPC for messages
 * Filesystem for data

https://github.com/andresriancho/w3af/commit/5d0bcd717bcbe770acbc9feaa280dff2770bb994 and the errors seem to have disappeared (at least with the first 30 scans). Thanks!
