### ISSUE TITLE
OSX TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by CrabbyPete** [noxdafox/pebble#3]
I keep getting this running from OSX 
Exception in thread task_scheduler:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/xxx/migrate/lib/python2.7/site-packages/pebble/process/pool.py", line 82, in task_scheduler_loop
    pool_manager.schedule(task)
  File "/xxx/migrate/lib/python2.7/site-packages/pebble/process/pool.py", line 141, in schedule
    self.worker_manager.dispatch(task)
  File "/xxx/migrate/lib/python2.7/site-packages/pebble/process/pool.py", line 252, in dispatch
    self.pool_channel.send(NewTask(task.number, task._metadata))
  File "/xxx/migrate/lib/python2.7/site-packages/pebble/process/channel.py", line 55, in send
    return self.writer.send(obj)
TypeError: 'NoneType' object is not callable

trying to run:
    pool = process.Pool()
    for q in query:
        job = pool.schedule( background, args=[source, destination, q ] )

**Comment by noxdafox** [comment]
Thank your for reporting the issue.

From the traceback it seems the channel is somehow not initialized and crashes when it tries to send a task through it. 

Is the issue showing up after immediately after you schedule the first task? Are you running the Pool in a separated Thread or Process?

**Comment by CrabbyPete** [comment]
Thanks, I think the issue is I am trying to pass 2 class objects as parameters and the queue is choking. It works for when I make it a process, but 
when I try and use a pool is when I get the error

**Comment by noxdafox** [comment]
From the traceback it seems a bit different. If I get it correct, the issue seems to be that the `Pipe.send` method is None which to me makes no sense.

Could you try to send the 2 objects via a regular Pipe and see if the issue shows as well?

from multiprocessing import Pipe

reader, writer = Pipe(duplex=False)
writer.send([source, destination, q])

Unfortunately I don't have a MAC so for I can't reproduce the issue. I could find one but I need some time.

**Comment by CrabbyPete** [comment]
I can’t pass a object with functions through a pipe. I made the objects global and it works fine. One problem I have though is if
one task gets and exception. It just hangs.

**Comment by noxdafox** [comment]
What does hang? Could you paste the complete code (on pastebin for example) so I can verify what is wrong?

As from the [documentation](http://pythonhosted.org/Pebble/#Task) you can call `task.get()` to get either the results or the exception which was raised within the worker.

If you do not want to block on `task.get()`, you can use a callback.

**Comment by noxdafox** [comment]
Hello, is this still valid?

**Comment by CrabbyPete** [comment]
No, I have it working now
