### ISSUE TITLE
Daemonic processes are not allowed to have children

### ISSUE THREAD

**Issue by warmspringwinds** [noxdafox/pebble#31]
Hi,

While working with your great library I have faced this problem -- one
of my process that was scheduled using the pool raised this exception:
```
Daemonic processes are not allowed to have children
```

Do you know if there is a fix for this?

**Comment by warmspringwinds** [comment]
@noxdafox Thank you for your reply!

I am spawning machine learning jobs that also spawn workers that load data
to make the job complete faster.

So far I have changed this line:
https://github.com/noxdafox/pebble/blob/master/pebble/common.py#L120

And it seems to work. Am I right that a problem might occur if my main process spawned a non
daemonic process that has children? And if I send a sigterm to the main process, I will have to wait
for its non-daemonic children to stop their children?

Thank you.

**Comment by noxdafox** [comment]
Note `Exception` is not a superclass of `KeyboardInterrupt` which is raised when `CTRL+C` is pressed [see docs](https://docs.python.org/2/library/exceptions.html#exception-hierarchy). You will need to capture that as well.

**Comment by warmspringwinds** [comment]
@noxdafox Thanks for pointing that out! :)

Keep up the great work on your library 👍

**Comment by Shellbye** [comment]
I came here because my unittest raises

    AssertionError: daemonic processes are not allowed to have children

This is because I have used `multiprocessing`.

After read what you guys discussed, I realize that  I did not `close` and `join` properly, after tiny modification everything is fine now.

Hope this help someone in the future. 😊

**Comment by Matrixsun** [comment]
> I came here because my unittest raises
> 
> ```
> AssertionError: daemonic processes are not allowed to have children
> ```
> 
> This is because I have used `multiprocessing`.
> 
> After read what you guys discussed, I realize that I did not `close` and `join` properly, after tiny modification everything is fine now.
> 
> Hope this help someone in the future. blush

Can you give a single demo example? Thanks
