### ISSUE TITLE
Pre-Fork ProcessPool?

### ISSUE THREAD

**Issue by jshlbrd** [noxdafox/pebble#36]
I'm having issues using Pebble's ProcessPool with gRPC (described here https://github.com/grpc/grpc/issues/18342) and a gRPC contributor suggested that it may be due to the processes in ProcessPool not being pre-forked (his comment is here https://github.com/grpc/grpc/issues/18342#issuecomment-472226047). Any thoughts on this and if pre-forking can be added as an option? gRPC requires any subprocesses to be forked before the gRPC server starts.

**Comment by noxdafox** [comment]
Hello,

@gnossen assumptions are correct. `pebble` pools lazily create processes the first time the application interacts with it. To enforce the process creation, you have to interact with it once. You can simply query its status once to create all processes.

```python
with pebble.ProcessPool() as pool:
    assert pool.active  # pre-forking here

    server = grpc.server( ... )

    pool.schedule(something)
```

**Comment by noxdafox** [comment]
Closing this issue as the linked one was closed.
