### ISSUE TITLE
add_done_callback() not passing the original task

### ISSUE THREAD

**Issue by k4ml** [noxdafox/pebble#38]
Based on the example on README, let say we have this:-

```python
from pebble import ProcessPool
from concurrent.futures import TimeoutError

def execute_task(task):
    # work on task
    ...
    task.status = 'done'
    task.save()

def task_done(future):
    try:
        result = future.result()  # blocks until results are ready
    except TimeoutError as error:
        print("Function took longer than %d seconds" % error.args[1])
    except Exception as error:
        print("Function raised %s" % error)
        print(error.traceback)  # traceback of the function

with ProcessPool(max_workers=5, max_tasks=10) as pool:
    for task in get_tasks():
        future = pool.schedule(execute_task, args=[task], timeout=3)
        future.add_done_callback(task_done)
```

So in case of time out for example, we may want to set `task.status = 'failed` but we don't have any reference to task from `task_done()` function. One workaround I can think of is with closure:-

```python
def task_done(future, task):
    try:
        result = future.result()  # blocks until results are ready
    except TimeoutError as error:
        print("Function took longer than %d seconds" % error.args[1])
        task.status = 'failed'
        task.save()
    except Exception as error:
        print("Function raised %s" % error)
        print(error.traceback)  # traceback of the function

with ProcessPool(max_workers=5, max_tasks=10) as pool:
    for task in get_tasks():
        def task_done_wrapper(future):
            task_done(future, task)
        future = pool.schedule(execute_task, args=[task], timeout=3)
        future.add_done_callback(task_done_wrapper)
```
But is this a viable solution?

**Comment by noxdafox** [comment]
A closure is one of the recommended ways to go. 

One alternative is to use the [`partial`](https://docs.python.org/3/library/functools.html#functools.partial) function.

```python
from functools import partial

def task_done(task, future):
    """"Note that `partial` prepends arguments to the function."""
    ...

with ProcessPool(...) as pool:
    for task in get_tasks():        
        future = pool.schedule(...)
        done_callback = partial(task_done, task)
        future.add_done_callback(task_done)
```

Other alternative is to append the extra data to the future object.
```python

def task_done(future):
    print(future.task)

with ProcessPool(...) as pool:
    for task in get_tasks():        
        future = pool.schedule(...)
        # Implicit
        future.task = task
        # explicit
        setattr(future, 'task', task)
        future.add_done_callback(task_done)
```

**Comment by k4ml** [comment]
Aaah, so it's the same future object that get passed to the callback. In this case I think setting attribute is the best solution then, eliminate the extra overhead of a function call.

**Comment by noxdafox** [comment]
Yes, it's the same future object.

**Comment by k4ml** [comment]
Is there possible race condition when calling `future.result()`? We noticed some mixed up where the task id from the task passed through add_done_callback() doesn't match the task id we got from `future.result()`. The task id supposed to be the same as the function that execute the task will always return the same task.

**Comment by noxdafox** [comment]
The `Future` object is the one provided by `concurrent.futures` Python module. Therefore, it provides the same guarantees of the stdlib when it comes to race conditions.

I have never observed race conditions in callbacks so it probably depends on how you are generating the Task Id. Are you using Python `id` primitive?

**Comment by k4ml** [comment]
Turn out it caused by closure late binding in python. So when task_done() get called, the current task in the scope probably already the next task in row. So the task_done_wrapper() function should actually be defined as:-

```python
def task_done_wrapper(future, task=task):
    task_done(future, task)
```
