### ISSUE TITLE
Exceptions at WorkerManager.dispatch level are supressed

### ISSUE THREAD

**Issue by rares-urdea** [noxdafox/pebble#47]
Hello!

I ran into an issue caused by a psycopg connection object that cannot be pickled when sending the task payload to the worker. I was eventually able to fix the root cause but the debugging process turned out to be quite tedious because I couldn't see where the actual exception was coming from.

Here's what I was able to find:
1. process.WorkerManager.dispatch attempts to send the task payload to the worker
```
    def dispatch(self, task):
        try:
            self.pool_channel.send(WorkerTask(task.id, task.payload))
        except (OSError, EnvironmentError, TypeError) as error:
            raise BrokenProcessPool(error)
```
2. The exception is re-raised and encapsulated by BrokenProcessPool (great!)
3. Since this is happening in the task_scheduler_loop:
```
    try:
        while context.alive:
            task = task_queue.get()

            if task is not None:
                if task.future.cancelled():
                    task.set_running_or_notify_cancel()
                    task_queue.task_done()
                else:
                    pool_manager.schedule(task)
            else:
                task_queue.task_done()
    except BrokenProcessPool:
        context.state = ERROR
```
the exception is caught and the state is set to `ERROR`, but the original message and trace are lost.
4. On the following `_check_pool_state` call, the state is `ERROR` and a new `RuntimeError` is raised, masking the root cause.

Ideally, the cause of the original exception would either be propagated and then included in the `RuntimeError` or just sent to stderr, logged, etc.

If this is in fact the expected behaviour and it should've been logged, I may have missed a step in the setup part (though I do not recall seeing anything in the docs). Please let me know if that's case, and thanks for the great work you've done with pebble!

**Comment by noxdafox** [comment]
Issue resolved in release `4.4.1`.
