### ISSUE TITLE
running on a mac causes exception using python 2.7

### ISSUE THREAD

**Issue by CrabbyPete** [noxdafox/pebble#5]
I am running on a mac and I get an exception running this code
   jobs = []
    with ProcessPool( max_workers = workers ) as pool:
        # background is the task that runs and the parameter to it follow
        for q in query:
            job = pool.schedule( background, args=( q, recursion, action, update ) ) 
            job.add_done_callback( finished )
            jobs.append(job)

  File "/Users/Dropbox/Work/adops/migrate/lib/python2.7/site-packages/pebble/pool/channel.py", line 44, in unix_poll
    return bool(select([self.reader], [], [], timeout)[0])
error: (9, 'Bad file descriptor')

**Comment by CrabbyPete** [comment]
It was a mistake I made going from the previous version that used get in the callback

**Comment by noxdafox** [comment]
The new version is based on `concurrent.futures.Future`.

To set a callback, you can use Future.add_done_callback.

**Comment by CrabbyPete** [comment]
Thanks, with the old version I could do  job.number to determine what job completed if I ran
a bunch of jobs. How do you know what job finished now?

**Comment by noxdafox** [comment]
You can use the Future Id or hash.

```
future = pool.schedule( ... )
id(future)
hash(future)
```

**Comment by CrabbyPete** [comment]
Great. Thank you
