### ISSUE TITLE
Feature Request: add `pebble.ProcessFuture.stop`

### ISSUE THREAD

**Issue by marxin** [noxdafox/pebble#59]
I would see it handy to be able to selectively `stop` a `ProcessFuture`.
Right now, one can only stop all of them with `pool.stop`. Note that I speak about processes where `stop` means abruptly.

Thanks!

**Comment by noxdafox** [comment]
This is already supported through the [`future.cancel()`](https://pebble.readthedocs.io/en/latest/#pebble.ProcessFuture.cancel) method.
