### ISSUE TITLE
Installing Pebble from pypi for Python 2.7 is broken

### ISSUE THREAD

**Issue by scole66** [noxdafox/pebble#6]
Installing Pebble via pip for Python 2.7 seems to be misconfigured.

To wit:
```
(venv) c:\Users\scole\Documents\ingress>pip install Pebble
Collecting Pebble
  Downloading Pebble-4.1.0-py2.py3-none-any.whl (49kB)
Installing collected packages: Pebble
Successfully installed Pebble-4.1.0

(venv) c:\Users\scole\Documents\ingress>python
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pebble
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Users\scole\Documents\ingress\venv\lib\site-packages\pebble\__init__.py", line 10, in <module>
    from pebble.pool.thread import ThreadPool
  File "c:\Users\scole\Documents\ingress\venv\lib\site-packages\pebble\pool\thread.py", line 21, in <module>
    from pebble.pool.base_pool import BasePool, run_initializer
  File "c:\Users\scole\Documents\ingress\venv\lib\site-packages\pebble\pool\base_pool.py", line 21, in <module>
    from concurrent.futures import Future, TimeoutError
ImportError: No module named concurrent.futures
>>> 
```

Now, I certainly see the stuff in the top level of this repo that tries to install `future`; it just hasn't happened for some reason. (I get this same error on both windows installs and linux installs.)

I'll take a look myself, but I haven't ever used setuptools before personally, so there's a bit of a learning curve there.

**Comment by noxdafox** [comment]
Thanks for reporting! I'll fix this ASAP.

In the meanwhile, you can workaround this by installing concurrent.futures manually from pip.

**Comment by noxdafox** [comment]
I managed to reproduce it and also found an interesting related article.

https://hynek.me/articles/conditional-python-dependencies/

I will fix it during the WE.

**Comment by scole66** [comment]
I'm not sure you need to go as far enabling conditional dependencies. It looked to me by reading documentation that it's harmless to have a python3 project require future. (I haven't tested this to confirm, however.)

**Comment by noxdafox** [comment]
Uploaded a new version of setup.py covering setuptools >= 18.0.

Please re-open the issue specifying your setuptools version if the problem persists.
