### ISSUE TITLE
Faster response with a lower value of SLEEP_UNIT

### ISSUE THREAD

**Issue by marxin** [noxdafox/pebble#65]
I am working a test-case reduction tool (https://github.com/marxin/cvise) where I create `ProcessPool`s and I commonly `cancel` process futures. I noticed that decreasing `SLEEP_UNIT` from `0.1` to `0.01` can speed up my workload:

From:
```
...
00:00:52 INFO (98.7%, 2934 bytes)
00:00:52 INFO (98.7%, 2917 bytes)
00:00:53 INFO (98.7%, 2899 bytes)
00:00:53 INFO (98.7%, 2870 bytes)
00:00:53 INFO (98.7%, 2833 bytes)
00:00:53 INFO (98.8%, 2744 bytes)
00:00:53 INFO ===< LinesPass::1 >===
```

To:
```
...
00:00:45 INFO (98.7%, 2870 bytes)
00:00:45 INFO (98.7%, 2833 bytes)
00:00:45 INFO (98.8%, 2744 bytes)
00:00:45 INFO ===< LinesPass::1 >===
```

Would it be possible to decrease the unit or have a parameter that can a library consumer control?
Thanks for working on the library!

**Comment by marxin** [comment]
One can adjust that easily with:
```python3
pebble.common.SLEEP_UNIT = 0.01
```

But maybe the project can offer some better control over the desired responsiveness.

**Comment by noxdafox** [comment]
Hello,

That is the correct way if you want to change such behaviour.

Please mind that decreasing the internal polling mechanism will put more stress on the main loop and might have undesirable consequences.

I am not going to expose the Pool internal mechanisms as it would break encapsulation and overly complicate Pebble APIs. Pebble aims to be a simple alternative to standard `mulitprocessing.Pool` and `concurrent.futures.Executor` with enhanced capabilities. If you need a fully controllable process pool, you can take a look at [billiard](https://pypi.org/project/billiard/).
