### ISSUE TITLE
Using pebble with inheritance, unexpected behaviour in concurrence decorator

### ISSUE THREAD

**Issue by derwyddon** [noxdafox/pebble#68]
I was trying to call external non-trusted subprocesses with the help of pebble. I was modelling it with children classes having two methods with the @Concurrent decorator (one in each child method that each one call a different subprocess with subprocess.run or http request, due a children uses a local library and the other one uses a api library). The problem is that the script is calling the method from the non-expected children (after reviewing twice the spelling).
I have reduced the code to a simple version in order to reproduce the problem.
[test_peeble_inheritance.zip](https://github.com/noxdafox/pebble/files/5000368/test_peeble_inheritance.zip)

If I call the attached script with the "-f apple -a eat" parameters I could get a stdout similar to this one (the original code is not really using prints and it is calling external processes) :
Fruit Init
Apple Init
Cherry Eat

**Comment by derwyddon** [comment]
I forget to mention the testing environment:
Win10 1803 x64
Python 3.7
Peeble 4.5.3

**Comment by derwyddon** [comment]
Using a tweak to avoid use the same name for the @concurrent methods is solving the issue as you could check running the attached tweaked script 
[test_peeble_inheritance_tweaked.zip](https://github.com/noxdafox/pebble/files/5001070/test_peeble_inheritance_tweaked.zip)
Could be the problem be related to the methods that has the same name (because they are children of the same parent class)?

**Comment by noxdafox** [comment]
Hello,

I cannot understand what is the problem here. What is the expected behaviour and what do you get instead?

**Comment by derwyddon** [comment]
With my environment I've got:

$ python3 test.py  -f apple -a eat
Fruit Init
Apple Init
**Cherry Eat**
THE END
                                                                                                 
$ python3 test.py  -f cherry -a eat
Fruit Init
Cherry Init
Cherry Eat
THE END

$ python3 test.py  -f apple -a collect
Fruit Init
Apple Init
**Cherry Collect**
THE END
                                                                                                 
$ python3 test.py  -f cherry -a collect
Fruit Init
Cherry Init
Cherry Collect
THE END

Also I've added a minor thing: sleep(1) before the last print to get the right printing order
[test_peeble_inheritance.txt](https://github.com/noxdafox/pebble/files/5005499/test_peeble_inheritance.txt)

**Comment by derwyddon** [comment]
And, If I remove the @concurrence decorator from the methods (what it is fine for the example, but not for the real case), I get the expected result.

**Comment by noxdafox** [comment]
I will need to grab a windows PC to reproduce this. I don't have any at hand currently.

**Comment by noxdafox** [comment]
Fix added in [release 4.6.0](https://github.com/noxdafox/pebble/releases/tag/4.6.0).

Closing this issue, please re-open it if the problem persists.
